import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#121412',
        surface: '#121412',
        'surface-dim': '#121412',
        'surface-bright': '#383a37',
        'surface-container-lowest': '#0d0f0d',
        'surface-container-low': '#1a1c1a',
        'surface-container': '#1e201e',
        'surface-container-high': '#292a28',
        'surface-container-highest': '#333533',
        'surface-variant': '#333533',
        'surface-tint': '#a0d494',
        'on-surface': '#e3e3df',
        'on-surface-variant': '#c2c9bb',
        'on-background': '#e3e3df',
        primary: '#a0d494',
        'primary-container': '#0f3d0e',
        'primary-fixed': '#bcf0ae',
        'primary-fixed-dim': '#a0d494',
        'on-primary': '#0a390a',
        'on-primary-container': '#78a96e',
        'on-primary-fixed': '#002202',
        'on-primary-fixed-variant': '#23501f',
        'inverse-primary': '#3b6935',
        secondary: '#ffb4aa',
        'secondary-container': '#e10211',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#ffb4aa',
        'on-secondary': '#690003',
        'on-secondary-container': '#fff1ef',
        'on-secondary-fixed': '#410001',
        'on-secondary-fixed-variant': '#930007',
        tertiary: '#e9c400',
        'tertiary-container': '#c9a900',
        'tertiary-fixed': '#ffe16d',
        'tertiary-fixed-dim': '#e9c400',
        'on-tertiary': '#3a3000',
        'on-tertiary-container': '#4c3f00',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#544600',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#8c9387',
        'outline-variant': '#42493f',
        'inverse-surface': '#e3e3df',
        'inverse-on-surface': '#2f312e',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
      },
      animation: {
        'pulse-slow': 'pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-fast': 'pulse 0.8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'bar-fill': 'barFill 1.2s ease-out forwards',
        'cheer-burst': 'cheerBurst 0.6s ease-out forwards',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        barFill: {
          '0%': { width: '0%' },
          '100%': { width: 'var(--bar-width)' },
        },
        cheerBurst: {
          '0%': {
            opacity: '1',
            transform: 'translate(-50%, -50%) rotate(var(--burst-angle)) translateY(0) scale(1)',
          },
          '100%': {
            opacity: '0',
            transform: 'translate(-50%, -50%) rotate(var(--burst-angle)) translateY(-36px) scale(0)',
          },
        },
      },
    },
  },
  plugins: [],
}

export default config
