/* global React */
// ─────────────────────────────────────────────
// TEAM DATA — World Cup 2026 contenders
// Each team has: identity, results, fixtures, squad,
// stats, prediction, narrative, h2h, trophy case
// ─────────────────────────────────────────────

window.TEAM_DATA = {
  BRA: {
    name: "Brazil", code: "BRA", short: "BRA",
    colors: ["#009C3B", "#FFDF00", "#002776"],
    primary: "#009C3B", accent: "#FFDF00",
    nickname: "Seleção",
    slogan: "Samba, reborn.",
    eyebrow: "GROUP B · POT 1 · ★★★★★",
    manager: "Dorival Júnior",
    captain: "Marquinhos",
    elo: 2147, eloTrend: +12, fifa: 2,
    rank: 1, world: 1, continent: "CONMEBOL",
    group: "B",
    record: { p: 7, w: 5, d: 1, l: 1, gf: 14, ga: 5 },
    form: ["W","W","D","W","W","W","L"],
    stats: {
      xG: 2.31, xGA: 0.94, possession: 58, ppg: 2.29,
      shotsPG: 16.4, savesPG: 3.1, cleanSheets: 4,
    },
    prediction: {
      winCup: 19.4, makeFinal: 31.2, semis: 48.7, quarters: 71.2,
      groupAdvance: 94.1, modelNote: "Top of Pot 1; Elo + xG difference both rank #1."
    },
    nextOpponent: { code: "ARG", date: "TONIGHT · 21:00", venue: "ESTÁDIO DO MARACANÃ" },
    fixtures: [
      { date: "MAY 12", opp: "ARG", venue: "MARACANÃ",     comp: "MD1", status: "tonight" },
      { date: "MAY 16", opp: "JPN", venue: "ESTÁDIO MANÉ", comp: "MD2", status: "scheduled" },
      { date: "MAY 21", opp: "NED", venue: "MORUMBI",      comp: "MD3", status: "scheduled" },
      { date: "MAY 27", opp: "TBD", venue: "TBD",          comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 28", opp: "ESP", res: "W 3-1", venue: "Wembley", comp: "Friendly" },
      { date: "APR 02", opp: "GER", res: "W 2-0", venue: "Munich",  comp: "Friendly" },
      { date: "MAR 22", opp: "FRA", res: "D 1-1", venue: "Paris",   comp: "Friendly" },
      { date: "MAR 18", opp: "ENG", res: "W 2-1", venue: "Wembley", comp: "Friendly" },
      { date: "FEB 05", opp: "POR", res: "L 1-2", venue: "Lisbon",  comp: "Friendly" },
    ],
    keyPlayers: [
      { name: "Vinícius Jr.",   pos: "LW",  age: 25, club: "Real Madrid",      goals: 9, assists: 6, rating: 8.4, role: "talisman" },
      { name: "Rodrygo",        pos: "RW",  age: 25, club: "Real Madrid",      goals: 6, assists: 5, rating: 8.1, role: "creator" },
      { name: "Casemiro",       pos: "DM",  age: 33, club: "Manchester Utd",   goals: 1, assists: 2, rating: 7.6, role: "anchor" },
      { name: "Marquinhos",     pos: "CB",  age: 31, club: "Paris SG",         goals: 0, assists: 0, rating: 7.8, role: "captain" },
      { name: "Alisson",        pos: "GK",  age: 33, club: "Liverpool",        goals: 0, assists: 0, rating: 7.9, role: "wall" },
      { name: "Endrick",        pos: "ST",  age: 19, club: "Real Madrid",      goals: 5, assists: 2, rating: 7.4, role: "spark" },
    ],
    narrative: {
      title: "The reset season",
      lede: "After 24 years without lifting it, Brazil arrives in '26 with the youngest attack of any contender and the calmest manager in CONMEBOL.",
      body: "Dorival has done what no manager since Tite first tried — flatten the ego hierarchy, trust the kids, and play with the press on. The Vinícius–Rodrygo–Endrick triangle is the most expensive front three in tournament history, and on tonight's evidence they have finally found a rhythm at international tempo. The questions remain at the base: Casemiro is one tournament older than he was in Qatar, and the lateral cover behind Marquinhos is thin. But Brazil have not arrived as the favorite in a decade. Today, they are.",
      byline: "ANALYSIS · J. RIBEIRO · 12 MAY 2026"
    },
    rivals: [
      { code: "ARG", w: 38, d: 25, l: 41, last: "L 0-1 (2022)" },
      { code: "FRA", w:  5, d:  3, l:  3, last: "D 1-1 (2026)" },
      { code: "ESP", w:  6, d:  3, l:  2, last: "W 3-1 (2026)" },
      { code: "GER", w:  4, d:  1, l:  5, last: "W 2-0 (2026)" },
    ],
    trophies: [
      { y: "1958", t: "World Cup" }, { y: "1962", t: "World Cup" }, { y: "1970", t: "World Cup" },
      { y: "1994", t: "World Cup" }, { y: "2002", t: "World Cup" },
      { y: "2019", t: "Copa América" }, { y: "2007", t: "Copa América" },
    ],
    vote: { winCup: 41, makeFinal: 67, eliminated: 9 },
  },

  ARG: {
    name: "Argentina", code: "ARG", short: "ARG",
    colors: ["#75AADB", "#FFFFFF", "#75AADB"],
    primary: "#6CACE4", accent: "#FFFFFF",
    nickname: "Albiceleste",
    slogan: "Defend the throne.",
    eyebrow: "GROUP C · POT 1 · ★★★★★",
    manager: "Lionel Scaloni",
    captain: "Lionel Messi",
    elo: 2138, eloTrend: -4, fifa: 1,
    rank: 2, world: 2, continent: "CONMEBOL",
    group: "C",
    record: { p: 7, w: 5, d: 2, l: 0, gf: 12, ga: 4 },
    form: ["W","D","W","W","W","D","W"],
    stats: { xG: 2.04, xGA: 0.81, possession: 56, ppg: 2.43, shotsPG: 14.7, savesPG: 3.4, cleanSheets: 5 },
    prediction: { winCup: 17.8, makeFinal: 29.6, semis: 46.1, quarters: 70.8, groupAdvance: 92.4, modelNote: "Champions carry tournament-experience prior; Messi minutes managed." },
    nextOpponent: { code: "BRA", date: "TONIGHT · 21:00", venue: "ESTÁDIO DO MARACANÃ" },
    fixtures: [
      { date: "MAY 12", opp: "BRA", venue: "MARACANÃ",   comp: "MD1", status: "tonight" },
      { date: "MAY 17", opp: "MEX", venue: "AZTECA",     comp: "MD2", status: "scheduled" },
      { date: "MAY 22", opp: "POL", venue: "ROSE BOWL",  comp: "MD3", status: "scheduled" },
      { date: "MAY 28", opp: "TBD", venue: "TBD",        comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 30", opp: "ITA", res: "W 2-0", venue: "Wembley", comp: "Finalissima" },
      { date: "APR 05", opp: "ESP", res: "D 1-1", venue: "Madrid",  comp: "Friendly" },
      { date: "MAR 24", opp: "URU", res: "W 1-0", venue: "Mvd.",    comp: "WCQ" },
      { date: "MAR 19", opp: "COL", res: "W 3-1", venue: "Bs As",   comp: "WCQ" },
      { date: "FEB 08", opp: "BRA", res: "D 2-2", venue: "Rio",     comp: "WCQ" },
    ],
    keyPlayers: [
      { name: "Lionel Messi",    pos: "RW", age: 38, club: "Inter Miami",   goals: 7, assists: 8, rating: 8.6, role: "talisman" },
      { name: "Lautaro Martínez", pos: "ST", age: 28, club: "Inter Milan",  goals: 8, assists: 1, rating: 8.0, role: "finisher" },
      { name: "Julián Álvarez",  pos: "ST", age: 26, club: "Atlético MAD",  goals: 6, assists: 4, rating: 8.1, role: "second-striker" },
      { name: "Enzo Fernández",  pos: "CM", age: 25, club: "Chelsea",       goals: 2, assists: 4, rating: 7.7, role: "metronome" },
      { name: "Cristian Romero", pos: "CB", age: 28, club: "Tottenham",     goals: 1, assists: 0, rating: 7.9, role: "enforcer" },
      { name: "Emi Martínez",    pos: "GK", age: 33, club: "Aston Villa",   goals: 0, assists: 0, rating: 8.2, role: "wall" },
    ],
    narrative: {
      title: "The last dance, again",
      lede: "Messi turns 39 next month. The squad around him has finally aged into a system that doesn't need him to be everything.",
      body: "Scaloni's masterstroke since Qatar has been resisting the urge to over-tune. Same shape, same spine, gradual transitions. Mac Allister and Enzo run the midfield Messi used to drag forward by himself; Álvarez and Lautaro alternate the burden of the false-nine duties. The squad arrives with the calmest mood of any favorite — and the most realistic expectation of going out in the semis if Messi's minutes have to be capped. But this is a knockout side built for one final knockout run.",
      byline: "ANALYSIS · M. SARMIENTO · 12 MAY 2026"
    },
    rivals: [
      { code: "BRA", w: 41, d: 25, l: 38, last: "W 1-0 (2022)" },
      { code: "FRA", w:  6, d:  3, l:  3, last: "W (P) (2022)" },
      { code: "GER", w:  9, d:  6, l:  7, last: "L 0-1 (2014)" },
      { code: "ESP", w:  9, d:  4, l: 10, last: "D 1-1 (2026)" },
    ],
    trophies: [
      { y: "1978", t: "World Cup" }, { y: "1986", t: "World Cup" }, { y: "2022", t: "World Cup" },
      { y: "2021", t: "Copa América" }, { y: "2024", t: "Copa América" }, { y: "1993", t: "Copa América" },
    ],
    vote: { winCup: 47, makeFinal: 71, eliminated: 7 },
  },

  FRA: {
    name: "France", code: "FRA", short: "FRA",
    colors: ["#002395", "#FFFFFF", "#ED2939"],
    primary: "#002395", accent: "#ED2939",
    nickname: "Les Bleus",
    slogan: "Power, restored.",
    eyebrow: "GROUP A · POT 1 · ★★★★★",
    manager: "Didier Deschamps",
    captain: "Kylian Mbappé",
    elo: 2118, eloTrend: +6, fifa: 3,
    rank: 3, world: 3, continent: "UEFA",
    group: "A",
    record: { p: 7, w: 5, d: 1, l: 1, gf: 16, ga: 6 },
    form: ["W","W","W","L","D","W","W"],
    stats: { xG: 2.18, xGA: 1.04, possession: 54, ppg: 2.29, shotsPG: 15.8, savesPG: 3.6, cleanSheets: 3 },
    prediction: { winCup: 16.2, makeFinal: 27.8, semis: 44.2, quarters: 68.4, groupAdvance: 91.7, modelNote: "Mbappé's xG individually higher than 22 federations' totals." },
    nextOpponent: { code: "GER", date: "MAY 14 · 20:00", venue: "ALLIANZ ARENA" },
    fixtures: [
      { date: "MAY 14", opp: "GER", venue: "ALLIANZ",     comp: "MD1", status: "scheduled" },
      { date: "MAY 18", opp: "BEL", venue: "STADE DE FR.", comp: "MD2", status: "scheduled" },
      { date: "MAY 23", opp: "JPN", venue: "PARC OL",     comp: "MD3", status: "scheduled" },
      { date: "MAY 29", opp: "TBD", venue: "TBD",         comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 26", opp: "POR", res: "W 2-1", venue: "Paris",  comp: "Friendly" },
      { date: "APR 02", opp: "NED", res: "W 4-1", venue: "Lyon",   comp: "Friendly" },
      { date: "MAR 22", opp: "BRA", res: "D 1-1", venue: "Paris",  comp: "Friendly" },
      { date: "MAR 18", opp: "GER", res: "L 1-2", venue: "Munich", comp: "Friendly" },
      { date: "FEB 04", opp: "ESP", res: "W 2-0", venue: "Paris",  comp: "UNL F4" },
    ],
    keyPlayers: [
      { name: "Kylian Mbappé",  pos: "ST", age: 27, club: "Real Madrid",  goals: 12, assists: 4, rating: 8.7, role: "talisman" },
      { name: "Antoine Griezmann", pos: "AM", age: 35, club: "Atlético MAD", goals: 4, assists: 7, rating: 8.0, role: "playmaker" },
      { name: "Aurélien Tchouaméni", pos: "DM", age: 26, club: "Real Madrid", goals: 1, assists: 1, rating: 7.7, role: "anchor" },
      { name: "Jules Koundé",   pos: "CB", age: 27, club: "Barcelona",    goals: 0, assists: 0, rating: 7.6, role: "defender" },
      { name: "William Saliba", pos: "CB", age: 25, club: "Arsenal",      goals: 1, assists: 0, rating: 8.1, role: "rock" },
      { name: "Mike Maignan",   pos: "GK", age: 30, club: "AC Milan",     goals: 0, assists: 0, rating: 7.8, role: "wall" },
    ],
    narrative: {
      title: "Built around Kylian, again",
      lede: "Two finals in three tournaments. Mbappé enters his peak alongside a defence that can mute almost anyone.",
      body: "Deschamps has won the argument over style years ago — France will sit, France will counter, and France will trust Mbappé to do something on the half-turn. What's changed this cycle is the back line: Saliba's last 12 months at Arsenal have been the best of any center-back on the continent. Tchouaméni and Camavinga give Deschamps options nobody else can match in transition. The doubts are upfront beyond Mbappé — and whether Griezmann still has 90 minutes in him every three days.",
      byline: "ANALYSIS · C. DUPONT · 12 MAY 2026"
    },
    rivals: [
      { code: "GER", w: 14, d:  9, l: 13, last: "L 1-2 (2026)" },
      { code: "ENG", w: 14, d:  5, l: 17, last: "W 2-1 (2022)" },
      { code: "BRA", w:  3, d:  3, l:  5, last: "D 1-1 (2026)" },
      { code: "ARG", w:  3, d:  3, l:  6, last: "L (P) (2022)" },
    ],
    trophies: [
      { y: "1998", t: "World Cup" }, { y: "2018", t: "World Cup" },
      { y: "1984", t: "Euro" }, { y: "2000", t: "Euro" }, { y: "2021", t: "Nations League" },
    ],
    vote: { winCup: 38, makeFinal: 64, eliminated: 11 },
  },

  ESP: {
    name: "Spain", code: "ESP", short: "ESP",
    colors: ["#AA151B", "#F1BF00", "#AA151B"],
    primary: "#AA151B", accent: "#F1BF00",
    nickname: "La Roja",
    slogan: "Tiki-taka, recoded.",
    eyebrow: "GROUP D · POT 1 · ★★★★",
    manager: "Luis de la Fuente",
    captain: "Rodri",
    elo: 2102, eloTrend: +18, fifa: 4,
    rank: 4, world: 4, continent: "UEFA",
    group: "D",
    record: { p: 7, w: 5, d: 1, l: 1, gf: 15, ga: 5 },
    form: ["W","W","W","W","L","D","W"],
    stats: { xG: 2.27, xGA: 0.92, possession: 64, ppg: 2.29, shotsPG: 17.2, savesPG: 2.8, cleanSheets: 4 },
    prediction: { winCup: 12.8, makeFinal: 22.4, semis: 38.6, quarters: 63.1, groupAdvance: 90.2, modelNote: "Reigning Euro champs; xG up 18% vs Qatar cycle." },
    nextOpponent: { code: "ENG", date: "MAY 13 · 20:00", venue: "WEMBLEY" },
    fixtures: [
      { date: "MAY 13", opp: "ENG", venue: "WEMBLEY",     comp: "MD1", status: "scheduled" },
      { date: "MAY 18", opp: "USA", venue: "AT&T",        comp: "MD2", status: "scheduled" },
      { date: "MAY 23", opp: "MAR", venue: "BERNABÉU",    comp: "MD3", status: "scheduled" },
      { date: "MAY 29", opp: "TBD", venue: "TBD",         comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 28", opp: "BRA", res: "L 1-3", venue: "Wembley", comp: "Friendly" },
      { date: "APR 05", opp: "ARG", res: "D 1-1", venue: "Madrid",  comp: "Friendly" },
      { date: "MAR 25", opp: "NED", res: "W 2-1", venue: "Mestalla",comp: "UNL" },
      { date: "MAR 21", opp: "ITA", res: "W 3-0", venue: "Naples",  comp: "Friendly" },
      { date: "FEB 04", opp: "FRA", res: "L 0-2", venue: "Paris",   comp: "UNL F4" },
    ],
    keyPlayers: [
      { name: "Rodri",         pos: "DM", age: 29, club: "Man City",     goals: 2, assists: 3, rating: 8.5, role: "captain" },
      { name: "Lamine Yamal",  pos: "RW", age: 18, club: "Barcelona",    goals: 6, assists: 7, rating: 8.4, role: "phenom" },
      { name: "Nico Williams", pos: "LW", age: 23, club: "Barcelona",    goals: 5, assists: 4, rating: 8.0, role: "starter" },
      { name: "Pedri",         pos: "CM", age: 23, club: "Barcelona",    goals: 1, assists: 5, rating: 8.1, role: "creator" },
      { name: "Álvaro Morata", pos: "ST", age: 33, club: "AC Milan",     goals: 5, assists: 1, rating: 7.5, role: "anchor" },
      { name: "Unai Simón",    pos: "GK", age: 28, club: "Athletic",     goals: 0, assists: 0, rating: 7.7, role: "wall" },
    ],
    narrative: {
      title: "The youngest old team",
      lede: "Euro 2024 was the audition. With Yamal and Nico Williams two years older, Spain is finally a knockout team that can break a low block.",
      body: "Spain spent ten years possessing the ball and not knowing what to do with it. Yamal solved that problem in 23 minutes against England in Berlin. The fundamentals are still there — Rodri controls tempo nobody else can match — but the team now has two players who can win a tie alone. The defensive line creaks against pace, and the bench at striker drops off sharply behind Morata. But this is the most balanced Spain since 2012, and they know it.",
      byline: "ANALYSIS · A. SUÁREZ · 12 MAY 2026"
    },
    rivals: [
      { code: "FRA", w: 16, d:  7, l: 14, last: "L 0-2 (2026)" },
      { code: "GER", w:  9, d:  6, l: 11, last: "W 2-1 (2024)" },
      { code: "ITA", w: 12, d: 14, l: 11, last: "W 3-0 (2026)" },
      { code: "ENG", w: 15, d:  6, l: 14, last: "W 2-1 (2024)" },
    ],
    trophies: [
      { y: "2010", t: "World Cup" },
      { y: "1964", t: "Euro" }, { y: "2008", t: "Euro" }, { y: "2012", t: "Euro" }, { y: "2024", t: "Euro" },
      { y: "2023", t: "Nations League" },
    ],
    vote: { winCup: 28, makeFinal: 52, eliminated: 14 },
  },

  ENG: {
    name: "England", code: "ENG", short: "ENG",
    colors: ["#FFFFFF", "#CE1124", "#FFFFFF"],
    primary: "#1E3A8A", accent: "#CE1124",
    nickname: "Three Lions",
    slogan: "Finish the job.",
    eyebrow: "GROUP E · POT 1 · ★★★★",
    manager: "Thomas Tuchel",
    captain: "Harry Kane",
    elo: 2076, eloTrend: +4, fifa: 5,
    rank: 5, world: 5, continent: "UEFA",
    group: "E",
    record: { p: 7, w: 4, d: 2, l: 1, gf: 11, ga: 5 },
    form: ["W","D","W","W","L","D","W"],
    stats: { xG: 1.84, xGA: 0.97, possession: 57, ppg: 2.00, shotsPG: 14.1, savesPG: 3.0, cleanSheets: 3 },
    prediction: { winCup: 9.7, makeFinal: 18.4, semis: 33.2, quarters: 58.6, groupAdvance: 88.4, modelNote: "Tuchel has sharpened press; finishing variance still high." },
    nextOpponent: { code: "ESP", date: "MAY 13 · 20:00", venue: "WEMBLEY" },
    fixtures: [
      { date: "MAY 13", opp: "ESP", venue: "WEMBLEY",      comp: "MD1", status: "scheduled" },
      { date: "MAY 17", opp: "DEN", venue: "PARKEN",       comp: "MD2", status: "scheduled" },
      { date: "MAY 22", opp: "SUI", venue: "ETIHAD",       comp: "MD3", status: "scheduled" },
      { date: "MAY 28", opp: "TBD", venue: "TBD",          comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 27", opp: "USA", res: "W 3-0", venue: "Wembley", comp: "Friendly" },
      { date: "APR 02", opp: "BEL", res: "D 1-1", venue: "Brussels",comp: "Friendly" },
      { date: "MAR 22", opp: "BRA", res: "L 1-2", venue: "Wembley", comp: "Friendly" },
      { date: "MAR 18", opp: "ITA", res: "W 2-1", venue: "Naples",  comp: "Q" },
      { date: "FEB 04", opp: "NED", res: "W 2-0", venue: "Wembley", comp: "UNL" },
    ],
    keyPlayers: [
      { name: "Harry Kane",   pos: "ST", age: 32, club: "Bayern",         goals: 9, assists: 3, rating: 8.3, role: "captain" },
      { name: "Jude Bellingham", pos: "AM", age: 22, club: "Real Madrid", goals: 5, assists: 6, rating: 8.5, role: "engine" },
      { name: "Bukayo Saka",  pos: "RW", age: 24, club: "Arsenal",        goals: 4, assists: 5, rating: 8.0, role: "starter" },
      { name: "Phil Foden",   pos: "AM", age: 25, club: "Man City",       goals: 3, assists: 4, rating: 7.8, role: "creator" },
      { name: "Declan Rice",  pos: "DM", age: 27, club: "Arsenal",        goals: 1, assists: 2, rating: 8.0, role: "anchor" },
      { name: "Jordan Pickford", pos: "GK", age: 32, club: "Everton",     goals: 0, assists: 0, rating: 7.5, role: "wall" },
    ],
    narrative: {
      title: "Tuchel's experiment",
      lede: "First foreign manager. Press-heavy system. The squad still oscillates between cautious and chaotic — which version arrives in June?",
      body: "Tuchel has done in nine months what Southgate refused to do in seven years — turn England into a high-pressing team that defends from the front. The results since March have been the best of any UEFA federation. The question hanging over them is still finishing in knockout rounds: the data says they should score; recent history says, against the elite, they don't. If Bellingham hits form and Kane stays fit, they go far. If either falters, they go home in a penalty shootout.",
      byline: "ANALYSIS · S. MORTIMER · 12 MAY 2026"
    },
    rivals: [
      { code: "FRA", w: 17, d:  5, l: 14, last: "L 1-2 (2022)" },
      { code: "GER", w: 13, d:  6, l: 14, last: "W 2-0 (2024)" },
      { code: "ITA", w:  9, d:  8, l: 11, last: "W 2-1 (2026)" },
      { code: "ESP", w: 14, d:  6, l: 15, last: "L 1-2 (2024)" },
    ],
    trophies: [
      { y: "1966", t: "World Cup" },
    ],
    vote: { winCup: 21, makeFinal: 44, eliminated: 18 },
  },

  GER: {
    name: "Germany", code: "GER", short: "GER",
    colors: ["#000000", "#DD0000", "#FFCE00"],
    primary: "#000000", accent: "#FFCE00",
    nickname: "Die Mannschaft",
    slogan: "The rebuild is over.",
    eyebrow: "GROUP F · POT 1 · ★★★★",
    manager: "Julian Nagelsmann",
    captain: "Joshua Kimmich",
    elo: 2068, eloTrend: +21, fifa: 6,
    rank: 6, world: 6, continent: "UEFA",
    group: "F",
    record: { p: 7, w: 5, d: 1, l: 1, gf: 14, ga: 6 },
    form: ["W","W","L","W","W","D","W"],
    stats: { xG: 2.11, xGA: 1.18, possession: 60, ppg: 2.29, shotsPG: 16.0, savesPG: 3.2, cleanSheets: 3 },
    prediction: { winCup: 8.4, makeFinal: 16.7, semis: 30.6, quarters: 55.8, groupAdvance: 87.3, modelNote: "Best Elo gain of any contender; defence still volatile." },
    nextOpponent: { code: "FRA", date: "MAY 14 · 20:00", venue: "ALLIANZ ARENA" },
    fixtures: [
      { date: "MAY 14", opp: "FRA", venue: "ALLIANZ",      comp: "MD1", status: "scheduled" },
      { date: "MAY 19", opp: "POL", venue: "BERLIN",       comp: "MD2", status: "scheduled" },
      { date: "MAY 24", opp: "GHA", venue: "HAMBURG",      comp: "MD3", status: "scheduled" },
      { date: "MAY 30", opp: "TBD", venue: "TBD",          comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 29", opp: "NED", res: "W 2-1", venue: "Munich",  comp: "Friendly" },
      { date: "APR 02", opp: "BRA", res: "L 0-2", venue: "Munich",  comp: "Friendly" },
      { date: "MAR 22", opp: "ENG", res: "L 0-2", venue: "Wembley", comp: "Friendly" },
      { date: "MAR 18", opp: "FRA", res: "W 2-1", venue: "Munich",  comp: "Friendly" },
      { date: "FEB 05", opp: "ITA", res: "W 3-1", venue: "Naples",  comp: "Friendly" },
    ],
    keyPlayers: [
      { name: "Florian Wirtz",  pos: "AM", age: 22, club: "Liverpool",   goals: 6, assists: 7, rating: 8.4, role: "phenom" },
      { name: "Jamal Musiala",  pos: "AM", age: 22, club: "Bayern",      goals: 5, assists: 4, rating: 8.2, role: "creator" },
      { name: "Joshua Kimmich", pos: "RB", age: 31, club: "Bayern",      goals: 2, assists: 6, rating: 8.0, role: "captain" },
      { name: "Kai Havertz",    pos: "ST", age: 26, club: "Arsenal",     goals: 5, assists: 3, rating: 7.7, role: "false 9" },
      { name: "Antonio Rüdiger", pos: "CB", age: 32, club: "Real Madrid",goals: 1, assists: 0, rating: 7.8, role: "rock" },
      { name: "Marc-André ter Stegen", pos: "GK", age: 33, club: "Barcelona", goals: 0, assists: 0, rating: 7.6, role: "wall" },
    ],
    narrative: {
      title: "A house, rebuilt",
      lede: "Two summers ago they were on the floor. Nagelsmann arrives at his home Cup with the most dynamic midfield in Europe.",
      body: "Wirtz–Musiala is the most explosive midfield pairing of any contender, full stop. Kimmich at right-back has freed him to do the things he can't do as a six. And Havertz playing as a false nine has resolved the striker question. The doubts are at the back: Rüdiger is excellent, but the cover behind him is two years younger and two years thinner. Germany's ceiling is a final at the Olympiastadion. Their floor is going out to a counter-attacking team in the quarters because the line stepped too high.",
      byline: "ANALYSIS · L. FISCHER · 12 MAY 2026"
    },
    rivals: [
      { code: "FRA", w: 13, d:  9, l: 14, last: "W 2-1 (2026)" },
      { code: "ENG", w: 14, d:  6, l: 13, last: "W 2-0 (2024)" },
      { code: "ITA", w: 15, d:  7, l: 16, last: "W 3-1 (2026)" },
      { code: "ARG", w:  7, d:  6, l:  9, last: "W 1-0 (2014)" },
    ],
    trophies: [
      { y: "1954", t: "World Cup" }, { y: "1974", t: "World Cup" }, { y: "1990", t: "World Cup" }, { y: "2014", t: "World Cup" },
      { y: "1972", t: "Euro" }, { y: "1980", t: "Euro" }, { y: "1996", t: "Euro" },
    ],
    vote: { winCup: 18, makeFinal: 40, eliminated: 22 },
  },

  POR: {
    name: "Portugal", code: "POR", short: "POR",
    colors: ["#046A38", "#DA291C", "#FFE900"],
    primary: "#046A38", accent: "#DA291C",
    nickname: "A Seleção",
    slogan: "Generation, golden.",
    eyebrow: "GROUP G · POT 1 · ★★★★",
    manager: "Roberto Martínez",
    captain: "Cristiano Ronaldo",
    elo: 2041, eloTrend: -2, fifa: 7,
    rank: 7, world: 7, continent: "UEFA",
    group: "G",
    record: { p: 7, w: 4, d: 2, l: 1, gf: 13, ga: 7 },
    form: ["W","W","D","L","W","D","W"],
    stats: { xG: 1.97, xGA: 1.14, possession: 58, ppg: 2.00, shotsPG: 15.2, savesPG: 3.4, cleanSheets: 2 },
    prediction: { winCup: 6.2, makeFinal: 13.1, semis: 25.7, quarters: 50.4, groupAdvance: 85.8, modelNote: "Squad depth top-3 in tournament; CR7 minutes managed." },
    nextOpponent: { code: "URU", date: "MAY 13 · 18:00", venue: "ESTÁDIO DA LUZ" },
    fixtures: [
      { date: "MAY 13", opp: "URU", venue: "ESTÁDIO DA LUZ", comp: "MD1", status: "scheduled" },
      { date: "MAY 18", opp: "CRO", venue: "DRAGÃO",         comp: "MD2", status: "scheduled" },
      { date: "MAY 23", opp: "USA", venue: "ROSE BOWL",      comp: "MD3", status: "scheduled" },
      { date: "MAY 29", opp: "TBD", venue: "TBD",            comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 26", opp: "FRA", res: "L 1-2", venue: "Paris",   comp: "Friendly" },
      { date: "APR 02", opp: "ESP", res: "D 1-1", venue: "Lisbon",  comp: "Friendly" },
      { date: "MAR 22", opp: "ITA", res: "W 2-0", venue: "Naples",  comp: "Friendly" },
      { date: "MAR 18", opp: "POL", res: "W 3-1", venue: "Warsaw",  comp: "Q" },
      { date: "FEB 05", opp: "BRA", res: "W 2-1", venue: "Lisbon",  comp: "Friendly" },
    ],
    keyPlayers: [
      { name: "Cristiano Ronaldo", pos: "ST", age: 41, club: "Al-Nassr",       goals: 7, assists: 2, rating: 7.6, role: "icon" },
      { name: "Bruno Fernandes",   pos: "AM", age: 31, club: "Manchester Utd", goals: 4, assists: 8, rating: 8.0, role: "captain-in-waiting" },
      { name: "Rúben Dias",        pos: "CB", age: 28, club: "Man City",       goals: 1, assists: 0, rating: 7.9, role: "rock" },
      { name: "Bernardo Silva",    pos: "AM", age: 31, club: "Man City",       goals: 3, assists: 5, rating: 8.0, role: "creator" },
      { name: "Rafael Leão",       pos: "LW", age: 26, club: "AC Milan",       goals: 5, assists: 3, rating: 7.8, role: "x-factor" },
      { name: "Diogo Costa",       pos: "GK", age: 26, club: "FC Porto",       goals: 0, assists: 0, rating: 7.7, role: "wall" },
    ],
    narrative: {
      title: "Final act",
      lede: "Ronaldo, 41. Pepe gone. A squad spilling over with talent has one last window to convert depth into a Cup.",
      body: "Martínez's first task has been the one everyone before him refused — phasing Ronaldo's minutes without phasing him out. The squad behind him is arguably the deepest in the tournament: three center-backs who'd start anywhere, a midfield of Bruno-Bernardo-Vitinha, and three wingers competing for two spots. The doubts are the spine of leadership after Pepe and the second-striker question if Ronaldo can't go 90. But Portugal's xG numbers in qualifiers were the third-best in Europe.",
      byline: "ANALYSIS · J. COSTA · 12 MAY 2026"
    },
    rivals: [
      { code: "ESP", w:  6, d:  4, l: 17, last: "D 1-1 (2026)" },
      { code: "FRA", w:  6, d:  5, l: 19, last: "L 1-2 (2026)" },
      { code: "BRA", w:  4, d:  3, l: 18, last: "W 2-1 (2026)" },
      { code: "GER", w:  1, d:  5, l: 11, last: "L 2-4 (2014)" },
    ],
    trophies: [
      { y: "2016", t: "Euro" }, { y: "2019", t: "Nations League" }, { y: "2025", t: "Nations League" },
    ],
    vote: { winCup: 14, makeFinal: 31, eliminated: 26 },
  },

  NED: {
    name: "Netherlands", code: "NED", short: "NED",
    colors: ["#AE1C28", "#FFFFFF", "#21468B"],
    primary: "#FF6900", accent: "#21468B",
    nickname: "Oranje",
    slogan: "The total game, again.",
    eyebrow: "GROUP H · POT 1 · ★★★",
    manager: "Ronald Koeman",
    captain: "Virgil van Dijk",
    elo: 2024, eloTrend: -8, fifa: 8,
    rank: 8, world: 8, continent: "UEFA",
    group: "H",
    record: { p: 7, w: 4, d: 1, l: 2, gf: 11, ga: 8 },
    form: ["W","L","W","D","W","L","W"],
    stats: { xG: 1.78, xGA: 1.27, possession: 59, ppg: 1.86, shotsPG: 13.6, savesPG: 3.7, cleanSheets: 2 },
    prediction: { winCup: 4.1, makeFinal: 9.6, semis: 20.1, quarters: 44.3, groupAdvance: 81.7, modelNote: "Veteran spine; transition defence the weak link." },
    nextOpponent: { code: "AUS", date: "MAY 13 · 17:00", venue: "JOHAN CRUIJFF" },
    fixtures: [
      { date: "MAY 13", opp: "AUS", venue: "CRUIJFF",     comp: "MD1", status: "scheduled" },
      { date: "MAY 18", opp: "EGY", venue: "DE KUIP",     comp: "MD2", status: "scheduled" },
      { date: "MAY 23", opp: "BRA", venue: "MORUMBI",     comp: "MD3", status: "scheduled" },
      { date: "MAY 29", opp: "TBD", venue: "TBD",         comp: "R16", status: "knockout" },
    ],
    recent: [
      { date: "APR 29", opp: "GER", res: "L 1-2", venue: "Munich",  comp: "Friendly" },
      { date: "APR 02", opp: "FRA", res: "L 1-4", venue: "Lyon",    comp: "Friendly" },
      { date: "MAR 25", opp: "ESP", res: "L 1-2", venue: "Mestalla",comp: "UNL" },
      { date: "MAR 21", opp: "BEL", res: "W 2-0", venue: "A'dam",   comp: "UNL" },
      { date: "FEB 04", opp: "ENG", res: "L 0-2", venue: "Wembley", comp: "UNL" },
    ],
    keyPlayers: [
      { name: "Virgil van Dijk",  pos: "CB", age: 34, club: "Liverpool",   goals: 1, assists: 0, rating: 7.9, role: "captain" },
      { name: "Frenkie de Jong",  pos: "CM", age: 28, club: "Barcelona",   goals: 1, assists: 3, rating: 7.8, role: "metronome" },
      { name: "Cody Gakpo",       pos: "LW", age: 26, club: "Liverpool",   goals: 5, assists: 3, rating: 7.6, role: "starter" },
      { name: "Memphis Depay",    pos: "ST", age: 32, club: "Corinthians", goals: 4, assists: 2, rating: 7.4, role: "talisman" },
      { name: "Xavi Simons",      pos: "AM", age: 22, club: "RB Leipzig",  goals: 3, assists: 4, rating: 7.9, role: "future" },
      { name: "Bart Verbruggen",  pos: "GK", age: 23, club: "Brighton",    goals: 0, assists: 0, rating: 7.4, role: "wall" },
    ],
    narrative: {
      title: "One last cycle for the spine",
      lede: "Van Dijk is 34. De Jong is at his peak. Between them, a generation that should already have lifted something.",
      body: "Oranje arrive carrying the same questions of the last decade: a back four that doesn't quite cope with elite pace, a forward line that doesn't quite finish what the midfield creates. Koeman has stabilized the floor — group-stage exits are unlikely — but the ceiling depends on whether Simons can fully take the No. 10 shirt from Depay and whether the front line can stretch the field without Bergwijn at full health.",
      byline: "ANALYSIS · K. VAN DER MEER · 12 MAY 2026"
    },
    rivals: [
      { code: "GER", w: 11, d:  9, l: 16, last: "L 1-2 (2026)" },
      { code: "BEL", w: 21, d: 11, l: 12, last: "W 2-0 (2026)" },
      { code: "FRA", w:  3, d:  6, l: 12, last: "L 1-4 (2026)" },
      { code: "ENG", w:  6, d:  4, l: 11, last: "L 0-2 (2026)" },
    ],
    trophies: [
      { y: "1988", t: "Euro" },
    ],
    vote: { winCup: 8, makeFinal: 22, eliminated: 38 },
  },
};

// Helper: get team list array sorted by rank
window.TEAM_LIST = Object.values(window.TEAM_DATA).sort((a, b) => a.rank - b.rank);

// Helper: lookup team by code (with fallback)
window.getTeam = function(code) {
  return window.TEAM_DATA[code] || window.TEAM_DATA.BRA;
};
