import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

const workspaceRoot = process.cwd()
const coreMigrationPath = path.resolve(
  workspaceRoot,
  'supabase/migrations/20260331000000_create_core_football_schema.sql'
)
const helperMigrationPath = path.resolve(
  workspaceRoot,
  'supabase/migrations/20260326000000_create_update_updated_at_function.sql'
)
const pushSubscriptionMigrationPath = path.resolve(
  workspaceRoot,
  'supabase/migrations/20260327_create_push_subscriptions.sql'
)
const packageJsonPath = path.resolve(workspaceRoot, 'package.json')
const schemaDocPath = path.resolve(workspaceRoot, 'supabase/core-football-schema.md')
const verifyScriptPath = path.resolve(workspaceRoot, 'supabase/verify-core-football-schema.sql')
const smokeScriptPath = path.resolve(workspaceRoot, 'supabase/smoke-core-football-schema.sql')
const applyShellPath = path.resolve(workspaceRoot, 'scripts/apply-core-football-schema.sh')
const validateShellPath = path.resolve(workspaceRoot, 'scripts/validate-core-football-schema.sh')
const verifyShellPath = path.resolve(workspaceRoot, 'scripts/verify-core-football-schema.sh')
const smokeShellPath = path.resolve(workspaceRoot, 'scripts/smoke-core-football-schema.sh')
const playerIntelMigrationPath = path.resolve(
  workspaceRoot,
  'supabase/migrations/20260403_create_signals_player_intel.sql'
)

const coreMigration = fs.readFileSync(coreMigrationPath, 'utf8')
const helperMigration = fs.readFileSync(helperMigrationPath, 'utf8')
const pushSubscriptionMigration = fs.readFileSync(pushSubscriptionMigrationPath, 'utf8')
const packageJson = fs.readFileSync(packageJsonPath, 'utf8')
const schemaDoc = fs.readFileSync(schemaDocPath, 'utf8')
const verifyScript = fs.readFileSync(verifyScriptPath, 'utf8')
const smokeScript = fs.readFileSync(smokeScriptPath, 'utf8')
const applyShell = fs.readFileSync(applyShellPath, 'utf8')
const validateShell = fs.readFileSync(validateShellPath, 'utf8')
const verifyShell = fs.readFileSync(verifyShellPath, 'utf8')
const smokeShell = fs.readFileSync(smokeShellPath, 'utf8')
const playerIntelMigration = fs.readFileSync(playerIntelMigrationPath, 'utf8')

describe('core football schema migration', () => {
  it('defines the required core football tables', () => {
    const requiredTables = [
      'teams',
      'players',
      'team_stats',
      'matches',
      'standings',
      'head_to_head',
      'predictions',
      'narratives',
      'signals',
      'player_intel',
      'team_chemistry',
    ]

    for (const table of requiredTables) {
      expect(coreMigration).toMatch(new RegExp(`create table if not exists ${table} \\(`))
    }
  })

  it('defines the shared updated_at helper before the existing push subscription trigger migration', () => {
    expect(helperMigration).toContain('create or replace function update_updated_at()')
    expect(pushSubscriptionMigration).toMatch(/execute function update_updated_at\(\)/i)
    expect(path.basename(helperMigrationPath) < path.basename(pushSubscriptionMigrationPath)).toBe(true)
  })

  it('supports unresolved knockout bracket slots in matches', () => {
    expect(coreMigration).toContain('home_placeholder_slug text')
    expect(coreMigration).toContain('away_placeholder_slug text')
    expect(coreMigration).toContain('num_nonnulls(home_team_id, home_placeholder_slug) = 1')
    expect(coreMigration).toContain('num_nonnulls(away_team_id, away_placeholder_slug) = 1')
    expect(coreMigration).toContain('create unique index if not exists idx_matches_unique_fixture')
    expect(coreMigration).toContain('coalesce(home_team_id::text, home_placeholder_slug)')
    expect(coreMigration).toContain('coalesce(away_team_id::text, away_placeholder_slug)')
  })

  it('reserves forward-compatible fields for ratings, passing stats, and player intel signals', () => {
    expect(coreMigration).toContain('elo_rating numeric(8,2)')
    expect(coreMigration).toContain('elo_rank integer')
    expect(coreMigration).toContain('create index if not exists idx_teams_elo_rank on teams(elo_rank);')
    expect(coreMigration).toContain('pass_completion_pct numeric(5,2)')
    expect(coreMigration).toContain('team_stats_pass_completion_range')
    expect(coreMigration).toContain("recent_signals jsonb not null default '[]'::jsonb")
    expect(coreMigration).toContain('last_signal_at timestamptz')
    expect(coreMigration).toContain('create index if not exists idx_player_intel_last_signal_at on player_intel(last_signal_at desc);')
    expect(coreMigration).toContain('create or replace function player_recent_signals_are_valid(payload jsonb)')
    expect(coreMigration).toContain("signal->>'type' in ('training', 'quote', 'data')")
    expect(coreMigration).toContain('constraint player_intel_recent_signals_valid check (player_recent_signals_are_valid(recent_signals))')
    expect(coreMigration).toContain("constraint signals_signal_type_valid check (")
    expect(coreMigration).toContain("signal_type in ('injury', 'transfer', 'form', 'tactical', 'sentiment')")
  })

  it('keeps narratives forward-compatible with the later publishing pipeline migration', () => {
    expect(coreMigration).toContain('cache_key text unique')
    expect(coreMigration).toContain('source_date date')
    expect(coreMigration).toContain('match_key text')
    expect(coreMigration).toContain('home_team_slug text')
    expect(coreMigration).toContain('away_team_slug text')
    expect(coreMigration).toContain('team_slug text')
    expect(coreMigration).toContain('player_slug text')
    expect(coreMigration).toContain('fact_hash text')
    expect(coreMigration).toContain("meta jsonb not null default '{}'::jsonb")
    expect(coreMigration).toContain('approved_at timestamptz')
    expect(coreMigration).toContain("status in ('draft', 'approved', 'published', 'archived')")
    expect(coreMigration).toContain('alter table narratives add column if not exists competition_code')
    expect(coreMigration).toContain('alter table narratives add column if not exists cache_key text;')
    expect(coreMigration).toContain('create unique index if not exists narratives_cache_key_idx on narratives(cache_key);')
    expect(coreMigration).toContain("conname = 'narratives_team_id_fkey'")
    expect(coreMigration).toContain("conname = 'narratives_player_id_fkey'")
    expect(coreMigration).toContain("conname = 'narratives_match_id_fkey'")
    expect(coreMigration).toContain('drop trigger if exists narratives_set_updated_at on narratives;')
  })

  it('defines current-snapshot compatibility views for teams, players, fixtures, and compare reads', () => {
    expect(coreMigration).toContain('create or replace view team_profiles_current as')
    expect(coreMigration).toContain('create or replace view player_profiles_current as')
    expect(coreMigration).toContain('create or replace view match_fixtures_current as')
    expect(coreMigration).toContain('create or replace view signal_feed_current as')
    expect(coreMigration).toContain('create or replace view power_rankings_current as')
    expect(coreMigration).toContain('create or replace view group_standings_current as')
    expect(coreMigration).toContain('create or replace view head_to_head_current as')
    expect(coreMigration).toContain('left join lateral (')
    expect(coreMigration).toContain("and p.prediction_type = 'match_outcome'")
    expect(coreMigration).toContain("coalesce(t.group_code, 'TBD') as \"group\"")
    expect(coreMigration).toContain('coalesce(t.fifa_ranking, 999) as "fifaRanking"')
    expect(coreMigration).toContain("coalesce(tc.chemistry, 50.0::numeric) as chemistry")
    expect(coreMigration).toContain("coalesce(t.coach_name, 'TBD') as \"coachName\"")
    expect(coreMigration).toContain('t.slug as "teamSlug"')
    expect(coreMigration).toContain("coalesce(p.club, 'Unknown club') as club")
    expect(coreMigration).toContain("when coalesce(pi.fitness_status, p.fitness_status) = 'unknown' then 'amber'")
    expect(coreMigration).toContain('end as "fitnessStatus"')
    expect(coreMigration).toContain("coalesce(pi.sentiment_score, p.sentiment_score, 50.0::numeric) as \"sentimentScore\"")
    expect(coreMigration).toContain('coalesce(home_team.slug, m.home_placeholder_slug) as home_team_slug')
    expect(coreMigration).toContain('coalesce(home_team.slug, m.home_placeholder_slug) as "homeTeamSlug"')
    expect(coreMigration).toContain("coalesce(m.group_code, '') as \"group\"")
    expect(coreMigration).toContain("coalesce(m.venue, 'TBD venue') as venue")
    expect(coreMigration).toContain('coalesce(latest_prediction.home_win_prob, 0.33333::numeric) as "homeWinProb"')
    expect(coreMigration).toContain('m.kickoff_utc as "kickoffUtc"')
    expect(coreMigration).toContain('coalesce(pi.recent_signals, \'[]\'::jsonb) as recent_signals')
    expect(coreMigration).toContain('s.signal_type as "type"')
    expect(coreMigration).toContain('coalesce(signal_team.slug, player_team.slug) as "teamSlug"')
    expect(coreMigration).toContain('jsonb_build_object(')
    expect(coreMigration).toContain('scored.power_score as "powerScore"')
    expect(coreMigration).toContain("when rank <= 6 then 'title_contender'")
    expect(coreMigration).toContain('latest.qualification_status as "qualificationStatus"')
    expect(coreMigration).toContain('join team_profiles_current tp on tp.id = latest.team_id')
    expect(coreMigration).toContain('raw_team_a.slug <= raw_team_b.slug as team_a_is_canonical')
    expect(coreMigration).toContain('as "matchupKey"')
    expect(coreMigration).toContain('as "compareSlug"')
    expect(coreMigration).toContain('as "teamASlug"')
    expect(coreMigration).toContain('as "teamAWins"')
    expect(coreMigration).toContain('as "lastResult"')
    expect(coreMigration).toContain('as "notableMeetings"')
  })

  it('keeps the legacy player-intel migration compatible with the imported core schema tables', () => {
    expect(playerIntelMigration).toContain("this migration only applies the compatible RLS surface and skips legacy indexes")
    expect(playerIntelMigration).toContain("table_name = 'signals'")
    expect(playerIntelMigration).toContain('table_schema = current_schema()')
    expect(playerIntelMigration).toContain("column_name = 'player_key'")
    expect(playerIntelMigration).toContain('drop policy if exists "Public can read signals" on signals;')
    expect(playerIntelMigration).toContain('drop policy if exists "Public can read player_intel" on player_intel;')
    expect(playerIntelMigration).toContain('drop trigger if exists signals_updated_at on signals;')
  })
})

describe('core football schema documentation', () => {
  it('documents the same forward-compatible fields and related issue signals', () => {
    expect(schemaDoc).toContain('elo_rating')
    expect(schemaDoc).toContain('elo_rank')
    expect(schemaDoc).toContain('pass_completion_pct')
    expect(schemaDoc).toContain('recent_signals')
    expect(schemaDoc).toContain('last_signal_at')
    expect(schemaDoc).toContain('ZON-8')
    expect(schemaDoc).toContain('ZON-9')
    expect(schemaDoc).toContain('home_placeholder_slug')
    expect(schemaDoc).toContain('away_placeholder_slug')
    expect(schemaDoc).toContain('camelCase')
    expect(schemaDoc).toContain('fifaRanking')
    expect(schemaDoc).toContain('homeTeamSlug')
    expect(schemaDoc).toContain('signal_feed_current')
    expect(schemaDoc).toContain('team JSON')
    expect(schemaDoc).toContain('power_rankings_current')
    expect(schemaDoc).toContain('powerScore')
    expect(schemaDoc).toContain('group_standings_current')
    expect(schemaDoc).toContain('qualificationStatus')
    expect(schemaDoc).toContain('head_to_head_current')
    expect(schemaDoc).toContain('matchupKey')
    expect(schemaDoc).toContain('compareSlug')
    expect(schemaDoc).toContain('teamAWins')
    expect(schemaDoc).toContain('notableMeetings')
    expect(schemaDoc).toContain('33/33/33')
    expect(schemaDoc).toContain('non-null defaults')
    expect(schemaDoc).toContain('normalizes raw `unknown` fitness values to `amber`')
    expect(schemaDoc).toContain('training`, `quote`, or `data')
    expect(schemaDoc).toContain('injury`, `transfer`, `form`, `tactical`, and `sentiment')
    expect(schemaDoc).toContain('cache_key')
    expect(schemaDoc).toContain('approved_at')
    expect(schemaDoc).toContain('archived')
  })

  it('documents which app surfaces map to each compatibility view', () => {
    expect(schemaDoc).toContain('## Consumer mapping')
    expect(schemaDoc).toContain('src/app/teams/[slug]/page.tsx')
    expect(schemaDoc).toContain('src/app/teams/[slug]/players/[playerSlug]/page.tsx')
    expect(schemaDoc).toContain('src/app/groups/[group]/page.tsx')
    expect(schemaDoc).toContain('src/app/power-rankings/page.tsx')
    expect(schemaDoc).toContain('src/app/compare/[matchup]/page.tsx')
    expect(schemaDoc).toContain('src/app/predictions/page.tsx')
    expect(schemaDoc).toContain('src/app/daily-briefing/page.tsx')
    expect(schemaDoc).toContain('Primary reads: `power_rankings_current`')
    expect(schemaDoc).toContain('Primary reads: `group_standings_current`, `match_fixtures_current`')
    expect(schemaDoc).toContain('Primary reads: `signal_feed_current`, `team_profiles_current`, `player_profiles_current`')
    expect(schemaDoc).toContain('Primary reads: `team_profiles_current`, `player_profiles_current`, `head_to_head_current`')
    expect(schemaDoc).toContain('Still static: `WorldCupHistory` sections remain backed by `src/data/world-cup-history.json`.')
    expect(schemaDoc).toContain('Still static: `WorldCupHistory` and synthetic `MarketIntelData` sections remain backed by JSON/helpers outside this migration.')
  })

  it('includes a reusable SQL verification script for runtime database checks', () => {
    expect(verifyScript).toContain('verify-core-football-schema.sql')
    expect(verifyScript).toContain('Missing helper function %.update_updated_at()')
    expect(verifyScript).toContain('Missing helper function %.player_recent_signals_are_valid(jsonb)')
    expect(verifyScript).toContain('idx_matches_unique_fixture')
    expect(verifyScript).toContain('idx_player_intel_last_signal_at')
    expect(verifyScript).toContain('Missing required foreign keys:')
    expect(verifyScript).toContain('players.team_id -> teams.id')
    expect(verifyScript).toContain('predictions.match_id -> matches.id')
    expect(verifyScript).toContain('Missing required unique keys:')
    expect(verifyScript).toContain('teams.slug')
    expect(verifyScript).toContain('player_intel.player_id,captured_at,model_version')
    expect(verifyScript).toContain('Missing required check constraints:')
    expect(verifyScript).toContain('player_intel.recent_signals shape')
    expect(verifyScript).toContain('signals.signal_type enum')
    expect(verifyScript).toContain('Missing required compatibility views:')
    expect(verifyScript).toContain('required_helper_function_count')
    expect(verifyScript).toContain('required_table_count')
    expect(verifyScript).toContain('required_foreign_key_count')
    expect(verifyScript).toContain('required_unique_key_count')
    expect(verifyScript).toContain('required_check_constraint_count')
    expect(verifyScript).toContain('required_view_count')
    expect(verifyScript).toContain('array_agg(att.attname::text order by cols.ord) as actual_columns')
    expect(verifyScript).toContain('signal_feed_current')
    expect(verifyScript).toContain('power_rankings_current')
    expect(verifyScript).toContain('group_standings_current')
    expect(verifyScript).toContain('head_to_head_current')
    expect(verifyScript).toContain('updated_at_trigger_count')
    expect(verifyShell).toContain('verify-core-football-schema.sql')
    expect(verifyShell).toContain('psql is required to run core football schema verification.')
    expect(verifyShell).toContain('TARGET_SCHEMA=name')
    expect(packageJson).toContain('"schema:verify": "bash scripts/verify-core-football-schema.sh"')
    expect(schemaDoc).toContain('verify-core-football-schema.sql')
    expect(schemaDoc).toContain('npm run schema:verify')
    expect(schemaDoc).toContain('key foreign keys')
    expect(schemaDoc).toContain('unique constraints')
  })

  it('includes a rollback-safe smoke script for minimal runtime inserts', () => {
    expect(smokeScript).toContain('begin;')
    expect(smokeScript).toContain('rollback;')
    expect(smokeScript).toContain("insert into teams (")
    expect(smokeScript).toContain("insert into players (")
    expect(smokeScript).toContain("insert into matches (")
    expect(smokeScript).toContain("insert into predictions (")
    expect(smokeScript).toContain('team_profiles_current did not expose the latest chemistry snapshot')
    expect(smokeScript).toContain('player_profiles_current did not expose the latest player intel snapshot')
    expect(smokeScript).toContain('match_fixtures_current did not expose the latest prediction payload')
    expect(smokeScript).toContain('signal_feed_current did not expose the expected daily-briefing signal shape')
    expect(smokeScript).toContain('power_rankings_current did not expose the expected computed ranking payload')
    expect(smokeScript).toContain('group_standings_current did not expose the expected latest standings payload')
    expect(smokeScript).toContain('head_to_head_current did not expose the expected compare-friendly matchup payload')
    expect(smokeScript).toContain('Expected matches_home_participant_present')
    expect(smokeScript).toContain('Expected idx_matches_unique_fixture')
    expect(smokeScript).toContain('Expected signals_signal_type_valid')
    expect(smokeScript).toContain('Expected player_intel_recent_signals_valid')
    expect(smokeScript).toContain('Expected signals_subject_present')
    expect(smokeScript).toContain('"group" = \'\'')
    expect(smokeScript).toContain('"homeWinProb" = 0.33333')
    expect(smokeScript).toContain('"type" = \'form\'')
    expect(smokeScript).toContain('"recentSignals" -> 0 ->> \'type\' = \'training\'')
    expect(smokeScript).toContain('smoke_team_count')
    expect(smokeShell).toContain('smoke-core-football-schema.sql')
    expect(smokeShell).toContain('psql is required to run core football schema smoke validation.')
    expect(smokeShell).toContain('TARGET_SCHEMA=name')
    expect(packageJson).toContain('"schema:smoke": "bash scripts/smoke-core-football-schema.sh"')
    expect(schemaDoc).toContain('smoke-core-football-schema.sql')
    expect(schemaDoc).toContain('npm run schema:smoke')
    expect(validateShell).toContain('verify-core-football-schema.sh')
    expect(validateShell).toContain('smoke-core-football-schema.sh')
    expect(validateShell).toContain('DATABASE_URL=postgres://... bash scripts/validate-core-football-schema.sh')
    expect(packageJson).toContain('"schema:validate": "bash scripts/validate-core-football-schema.sh"')
    expect(schemaDoc).toContain('npm run schema:validate')
    expect(schemaDoc).toContain('team_profiles_current')
    expect(schemaDoc).toContain('player_profiles_current')
    expect(schemaDoc).toContain('match_fixtures_current')
    expect(schemaDoc).toContain('head_to_head_current')
  })

  it('includes an empty-database apply wrapper and a one-shot validate flow', () => {
    expect(applyShell).toContain("find \"$MIGRATIONS_DIR\" -maxdepth 1 -type f -name '*.sql' | sort")
    expect(applyShell).toContain('No SQL migrations were found under $MIGRATIONS_DIR.')
    expect(applyShell).toContain('TARGET_SCHEMA=name')
    expect(applyShell).toContain('psql is required to apply the core football schema migrations.')
    expect(applyShell).toContain('fresh or disposable database')
    expect(applyShell).toContain('not guaranteed to be safely re-runnable')
    expect(applyShell).toContain('DATABASE_URL=postgres://... bash scripts/apply-core-football-schema.sh')
    expect(validateShell).toContain('apply-core-football-schema.sh')
    expect(validateShell).toContain('verify-core-football-schema.sh')
    expect(validateShell).toContain('smoke-core-football-schema.sh')
    expect(validateShell).toContain('fresh or disposable database')
    expect(packageJson).toContain('"schema:apply": "bash scripts/apply-core-football-schema.sh"')
    expect(packageJson).toContain('"schema:validate": "bash scripts/validate-core-football-schema.sh"')
    expect(schemaDoc).toContain('scripts/apply-core-football-schema.sh')
    expect(schemaDoc).toContain('npm run schema:apply')
    expect(schemaDoc).toContain('npm run schema:validate')
    expect(schemaDoc).toContain('20260326000000_create_update_updated_at_function.sql')
    expect(schemaDoc).toContain('20260327_create_affiliate_clicks.sql')
    expect(schemaDoc).toContain('20260327_create_push_subscriptions.sql')
    expect(schemaDoc).toContain('20260331000000_create_core_football_schema.sql')
    expect(schemaDoc).toContain('fresh or disposable database')
  })
})
